# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: sensors.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database

# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(
    b'\n\rsensors.proto\x12\x0e\x63om.splunk.iot\x1a\x1fgoogle/protobuf/timestamp.proto"\\\n\x0eSensorSettings\x12\x19\n\x11is_sensor_enabled\x18\x01 \x01(\x08\x12\x1a\n\x12is_anomaly_enabled\x18\x02 \x01(\x08\x12\x13\n\x0bupload_rate\x18\x03 \x01(\r"9\n\rSensorChannel\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x0c\n\x04unit\x18\x02 \x01(\t\x12\x0c\n\x04type\x18\x03 \x01(\t"-\n\x0fSensorDimension\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t"\xb6\x02\n\x0fSensorDatapoint\x12-\n\ttimestamp\x18\x01 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12\r\n\x05value\x18\x02 \x01(\x02\x12.\n\x07\x63hannel\x18\x03 \x01(\x0b\x32\x1d.com.splunk.iot.SensorChannel\x12\x19\n\x11is_sensor_enabled\x18\x04 \x01(\x08\x12\x1a\n\x12is_anomaly_enabled\x18\x05 \x01(\x08\x12\x1f\n\x12\x61\x64\x64itional_details\x18\x06 \x01(\x0cH\x00\x88\x01\x01\x12\x33\n\ndimensions\x18\x07 \x03(\x0b\x32\x1f.com.splunk.iot.SensorDimension\x12\x11\n\tsensor_id\x18\x08 \x01(\tB\x15\n\x13_additional_details"]\n\x1a\x45xternalSensorAvailability\x12\x0f\n\x07metrics\x18\x01 \x03(\t\x12\x0c\n\x04type\x18\x02 \x01(\t\x12\n\n\x02id\x18\x03 \x01(\t\x12\x14\n\x0cis_available\x18\x04 \x01(\x08"\x94\x02\n\nSensorInfo\x12\n\n\x02id\x18\x01 \x01(\t\x12\x0c\n\x04type\x18\x02 \x01(\t\x12\x14\n\x0csensor_class\x18\x03 \x01(\t\x12\x11\n\tfile_name\x18\x04 \x01(\t\x12\x0c\n\x04port\x18\x05 \x01(\t\x12\x38\n\x07metrics\x18\x06 \x03(\x0b\x32\'.com.splunk.iot.SensorInfo.SensorMetric\x12\x30\n\x08settings\x18\x07 \x01(\x0b\x32\x1e.com.splunk.iot.SensorSettings\x1aI\n\x0cSensorMetric\x12\x13\n\x0bmetric_name\x18\x01 \x01(\t\x12\x11\n\tmin_range\x18\x02 \x01(\x02\x12\x11\n\tmax_range\x18\x03 \x01(\x02";\n\x0cSensorConfig\x12+\n\x07sensors\x18\x01 \x03(\x0b\x32\x1a.com.splunk.iot.SensorInfob\x06proto3'
)

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, "sensors_pb2", globals())
if _descriptor._USE_C_DESCRIPTORS == False:

    DESCRIPTOR._options = None
    _SENSORSETTINGS._serialized_start = 66
    _SENSORSETTINGS._serialized_end = 158
    _SENSORCHANNEL._serialized_start = 160
    _SENSORCHANNEL._serialized_end = 217
    _SENSORDIMENSION._serialized_start = 219
    _SENSORDIMENSION._serialized_end = 264
    _SENSORDATAPOINT._serialized_start = 267
    _SENSORDATAPOINT._serialized_end = 577
    _EXTERNALSENSORAVAILABILITY._serialized_start = 579
    _EXTERNALSENSORAVAILABILITY._serialized_end = 672
    _SENSORINFO._serialized_start = 675
    _SENSORINFO._serialized_end = 951
    _SENSORINFO_SENSORMETRIC._serialized_start = 878
    _SENSORINFO_SENSORMETRIC._serialized_end = 951
    _SENSORCONFIG._serialized_start = 953
    _SENSORCONFIG._serialized_end = 1012
# @@protoc_insertion_point(module_scope)
