share:
  fields:
    device_id:
      required: true
      selector:
        device:
          integration: tessie
    value:
      required: true
      selector:
        text:
    locale:
      required: false
      default: en-us
      selector:
        text:
